/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.espe.Product.view;
import ec.edu.espe.Product.model.ProductDao;
import ec.edu.espe.Product.model.Product;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author Pablo Collaguazo
 */
public class FrmProduct extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmProduct.class.getName());
     private static final double IVA = 0.15;
     private double subtotal = 0;
     private double iva = 0;
     private double total = 0;


    /**
     * Creates new form FrmProduct
     */
    public FrmProduct() {
        initComponents();
         txtsubtotal.setEditable(false);
         txtiva.setEditable(false);
         txttotal.setEditable(false);
         
    }
   private void cargarProductosDesdeMongo() {
        ProductDao dao = new ProductDao();
        ArrayList<Product> products = dao.getAllProducts();

        StringBuilder texto = new StringBuilder();
        for (Product p : products) {
            texto.append("ID: ").append(p.getId()).append("\n");
            texto.append("Producto: ").append(p.getName()).append("\n");
            texto.append("Cantidad: ").append(p.getQuantity()).append("\n");
            texto.append("Precio: ").append(p.getPrice()).append("\n");
            texto.append("Subtotal: ").append(String.format("%.2f", p.getSubtotal())).append("\n");
            texto.append("IVA: ").append(String.format("%.2f", p.getIva())).append("\n");
            texto.append("Total: ").append(String.format("%.2f", p.getTotal())).append("\n");
            texto.append("----------------------------\n");
        }
        txtareaproducts.setText(texto.toString());
    }


   private void calcularTotales() {
        try {
            int cantidad = Integer.parseInt(txtcantidad.getText());
            double precio = Double.parseDouble(txtprice.getText());

            double subtotal = cantidad * precio;
            double iva = subtotal * IVA;
            double total = subtotal + iva;

            txtsubtotal.setText(String.format("%.2f", subtotal));
            txtiva.setText(String.format("%.2f", iva));
            txttotal.setText(String.format("%.2f", total));
        } catch (NumberFormatException e) {
            txtsubtotal.setText("0.00");
            txtiva.setText("0.00");
            txttotal.setText("0.00");
        }
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblproducts = new javax.swing.JLabel();
        lblproduct = new javax.swing.JLabel();
        lblprice = new javax.swing.JLabel();
        lblsubtotal = new javax.swing.JLabel();
        lbltotal = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtsubtotal = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        lbliva = new javax.swing.JLabel();
        txtiva = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaproducts = new javax.swing.JTextArea();
        btnviewproducts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblproducts.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblproducts.setText("Productos");
        lblproducts.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblproduct.setText("Producto");

        lblprice.setText("Precio");

        lblsubtotal.setText("Subtotal");

        lbltotal.setText("Total");

        txtprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpriceKeyReleased(evt);
            }
        });

        txtsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubtotalActionPerformed(evt);
            }
        });

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });

        lbliva.setText("Iva");

        txtiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtivaActionPerformed(evt);
            }
        });

        btnsave.setText("Guardar");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btndelete.setText("Eliminar");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad");

        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcantidadKeyReleased(evt);
            }
        });

        txtareaproducts.setColumns(20);
        txtareaproducts.setRows(5);
        jScrollPane1.setViewportView(txtareaproducts);

        btnviewproducts.setText("Mostrar Productos");
        btnviewproducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewproductsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(txtiva, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbliva, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblprice, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblproduct, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(42, 42, 42)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblproducts, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btndelete)
                .addGap(48, 48, 48)
                .addComponent(btnviewproducts)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblproducts, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblproduct)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblprice)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblsubtotal)
                            .addComponent(txtiva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbliva)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltotal)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndelete)
                    .addComponent(btnsave)
                    .addComponent(btnviewproducts))
                .addGap(145, 145, 145))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubtotalActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalActionPerformed

    private void txtivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtivaActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
     
    guardarProducto();
    calcularTotales(); 
    

   // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
    
    eliminarProducto();
  

    // TODO add your handling code here:
    }//GEN-LAST:event_btndeleteActionPerformed

    private void txtcantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyReleased
    calcularTotales();   // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadKeyReleased

    private void txtpriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpriceKeyReleased
    calcularTotales();    // TODO add your handling code here:
    }//GEN-LAST:event_txtpriceKeyReleased

    private void btnviewproductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewproductsActionPerformed
    cargarProductosDesdeMongo();
    // TODO add your handling code here:
    }//GEN-LAST:event_btnviewproductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmProduct().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnviewproducts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbliva;
    private javax.swing.JLabel lblprice;
    private javax.swing.JLabel lblproduct;
    private javax.swing.JLabel lblproducts;
    private javax.swing.JLabel lblsubtotal;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JTextArea txtareaproducts;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtiva;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables

    private void cargarProductos() {
        try {
        ProductDao dao = new ProductDao();
        ArrayList<Product> products = dao.getAllProducts();

        txtareaproducts.setText(""); // limpiar JTextArea

        for (Product p : products) {
            txtareaproducts.append("ID: " + p.getId() + "\n");
            txtareaproducts.append("Nombre: " + p.getName() + "\n");
            txtareaproducts.append("Cantidad: " + p.getQuantity() + "\n");
            txtareaproducts.append("Precio: " + p.getPrice() + "\n");
            txtareaproducts.append("Subtotal: " + p.getSubtotal() + "\n");
            txtareaproducts.append("IVA: " + p.getIva() + "\n");
            txtareaproducts.append("Total: " + p.getTotal() + "\n");
            txtareaproducts.append("---------------------------\n");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error cargando productos: " + e.getMessage());
    }
}
    
      
      

    private void guardarProducto() {
         try {
        // 1️⃣ Leer datos de los campos de texto
        String nombre = txtname.getText();
        int cantidad = Integer.parseInt(txtcantidad.getText());
        double precio = Double.parseDouble(txtprice.getText());

        // 2️⃣ Crear el objeto Product
        Product product = new Product(nombre, cantidad, precio);
        product.calculateValues(); // recalcula subtotal, iva y total

        // 3️⃣ Guardar en MongoDB
        ProductDao dao = new ProductDao();
        dao.insert(product);

        JOptionPane.showMessageDialog(this, "Producto guardado correctamente");

        // 4️⃣ Mostrar todos los productos en el JTextArea
        cargarProductosDesdeMongo();

        // 5️⃣ Limpiar campos de entrada
        txtname.setText("");
        txtcantidad.setText("");
        txtprice.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Cantidad y Precio deben ser números válidos");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar el producto: " + e.getMessage());
    }
}

    private void eliminarProducto() {
          try {
        // 1️⃣ Pedir al usuario el ID del producto a eliminar
        String idStr = JOptionPane.showInputDialog(this, "Ingrese el ID del producto a eliminar:");
        if (idStr == null || idStr.isEmpty()) {
            return; // usuario canceló o dejó vacío
        }

        int id = Integer.parseInt(idStr);

        // 2️⃣ Llamar a ProductDao para eliminar
        ProductDao dao = new ProductDao();
        dao.delete(id);

        JOptionPane.showMessageDialog(this, "Producto eliminado correctamente");

        // 3️⃣ Volver a cargar los productos en el JTextArea
        cargarProductosDesdeMongo();

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID inválido. Debe ser un número entero.");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar el producto: " + e.getMessage());
    }
}
   
        
}
