package ec.edu.espe.contacts.view;

import ec.edu.espe.contacts.controller.ContactController;
import ec.edu.espe.contacts.model.Contact;
import ec.edu.espe.contacts.utils.CurrencyFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Mateo Aymacaña, T.A.P. (The Art of Programming), @ESPE
 */
public class FrmSearchId extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmSearchId.class.getName());

    private ContactController contactController;
    
    /**
     * Creates new form FrmSearchId
     */
    public FrmSearchId() {
        initComponents();
        contactController = new ContactController();
        configureTable();
        clearTable(); 
    }
    
    private void configureTable() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return String.class;
            }
            
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        String[] columnNames = {
            "ID", 
            "Full Name", 
            "Email", 
            "Type", 
            "Discount", 
            "Total Sale", 
            "Final Price", 
            "Savings"
        };
        
        model.setColumnIdentifiers(columnNames);
        tblResult.setModel(model);
        
        tblResult.setRowSorter(new TableRowSorter<>(model));
        
        if (tblResult.getColumnModel().getColumnCount() >= 8) {
            tblResult.getColumnModel().getColumn(0).setPreferredWidth(50);   
            tblResult.getColumnModel().getColumn(1).setPreferredWidth(150);   
            tblResult.getColumnModel().getColumn(2).setPreferredWidth(200);   
            tblResult.getColumnModel().getColumn(3).setPreferredWidth(80);    
            tblResult.getColumnModel().getColumn(4).setPreferredWidth(80);    
            tblResult.getColumnModel().getColumn(5).setPreferredWidth(100);   
            tblResult.getColumnModel().getColumn(6).setPreferredWidth(100);  
            tblResult.getColumnModel().getColumn(7).setPreferredWidth(100);   
        }
    }
    
    private void clearTable() {
        DefaultTableModel model = (DefaultTableModel) tblResult.getModel();
        model.setRowCount(0);
        
        if (lblMessage != null) {
            lblMessage.setText("Enter an ID and click Search");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtContactId = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        lblMessage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemReturnMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Search by Id");

        jLabel2.setText("Enter the ID:");

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Full Name", "Type", "Discount", "Total Sale", "Final Price", "Saving"
            }
        ));
        jScrollPane1.setViewportView(tblResult);

        lblMessage.setText("jLabel3");

        jMenu1.setText("System");

        itemReturnMenu.setText("Return to Menu");
        itemReturnMenu.addActionListener(this::itemReturnMenuActionPerformed);
        jMenu1.add(itemReturnMenu);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContactId, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch)))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(252, 252, 252))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContactId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(lblMessage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemReturnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReturnMenuActionPerformed
        FrmMenu frmMenu = new FrmMenu();
        frmMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemReturnMenuActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        searchContactById();
    }//GEN-LAST:event_btnSearchActionPerformed

     private void searchContactById() {
        try {
            String idText = txtContactId.getText().trim();
            
            if (idText.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "Please enter a contact ID",
                    "Input Required",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int contactId;
            try {
                contactId = Integer.parseInt(idText);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                    "Please enter a valid number for ID",
                    "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (contactId <= 0) {
                JOptionPane.showMessageDialog(this,
                    "ID must be a positive number",
                    "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Contact contact = contactController.getContactById(contactId);
            
            DefaultTableModel model = (DefaultTableModel) tblResult.getModel();
            model.setRowCount(0);
            
            model.addRow(new Object[]{
                contact.getId(),
                contact.getFullName(),
                contact.getEmail(),
                contact.getType().getDisplayName(),
                contact.getDiscount() + "%",
                CurrencyFormatter.format(contact.getTotalSale()),
                CurrencyFormatter.format(contact.calculateFinalPrice()),
                CurrencyFormatter.format(contact.getSavings())
            });
            
            if (lblMessage != null) {
                lblMessage.setText("Contact found: " + contact.getFullName());
            }
            
            JOptionPane.showMessageDialog(this,
                "Contact found successfully!",
                "Search Result",
                JOptionPane.INFORMATION_MESSAGE);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid number for ID",
                "Invalid Input",
                JOptionPane.ERROR_MESSAGE);
            
        } catch (Exception e) {
            DefaultTableModel model = (DefaultTableModel) tblResult.getModel();
            model.setRowCount(0);
            
            if (lblMessage != null) {
                lblMessage.setText("Contact not found");
            }
            
            JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(),
                "Search Failed",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmSearchId().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JMenuItem itemReturnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextField txtContactId;
    // End of variables declaration//GEN-END:variables
}
