package ec.edu.espe.hw29system.view;
import ec.edu.espe.hw29system.controller.PhotographerController;
import ec.edu.espe.hw29system.model.Photographer;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author Kevin Chalan, OBJECT MASTER, OOP
 */
public class FrmContrat extends javax.swing.JFrame {
    private final PhotographerController controller = new PhotographerController();
    private List<Photographer> photographersList;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmContrat.class.getName());

    /**
     * Creates new form FrmContrat
     */
    public FrmContrat() {
        initComponents();
        this.setLocationRelativeTo(null); 
        configureSpinner();               
        loadPhotographersCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1photographerlist = new javax.swing.JComboBox<>();
        jSpinner1and5horurs = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1contrat = new javax.swing.JButton();
        jButton2mainmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1photographerlist.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1photographerlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1photographerlistActionPerformed(evt);
            }
        });

        jLabel1.setText("SELECT PHOTOGRAPHER");

        jLabel2.setText("CONTRACT HOURS ( BETWEEN 1 AND 5 HOURS)");

        jButton1contrat.setText("CONTRAT");
        jButton1contrat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1contratActionPerformed(evt);
            }
        });

        jButton2mainmenu.setText("MAIN MENU");
        jButton2mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2mainmenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jComboBox1photographerlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jSpinner1and5horurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1contrat)
                                .addGap(74, 74, 74)
                                .addComponent(jButton2mainmenu))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1photographerlist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSpinner1and5horurs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1contrat)
                    .addComponent(jButton2mainmenu))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1contratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1contratActionPerformed
        String selectedName = (String) jComboBox1photographerlist.getSelectedItem();
        
        if (selectedName == null) {
            JOptionPane.showMessageDialog(this, "Select a photographer first!");
            return;
        }


        double hourlyRate = 0;
        Photographer selectedPhotographer = null;
        
        for (Photographer p : photographersList) {
            if (p.getName().equals(selectedName)) {
                hourlyRate = p.getHourlyRate();
                selectedPhotographer = p;
                break;
            }
        }
 
        if (selectedPhotographer != null) {
            int hours = (int) jSpinner1and5horurs.getValue();
            double totalCost = hourlyRate * hours;
            
   
            String message = String.format(
                "CONTRACT SUMMARY:\n" +
                "Photographer: %s\n" +
                "Rate: $%.2f /hr\n" +
                "Hours: %d\n" +
                "TOTAL TO PAY: $%.2f", 
                selectedName, hourlyRate, hours, totalCost
            );
            
            JOptionPane.showMessageDialog(this, message, "Contract Calculation", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1contratActionPerformed

    private void jButton2mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2mainmenuActionPerformed
       FrmMain frmMain = new FrmMain();
        frmMain.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2mainmenuActionPerformed

    private void jComboBox1photographerlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1photographerlistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1photographerlistActionPerformed

    
    private void configureSpinner() {
       
        SpinnerNumberModel model = new SpinnerNumberModel(1, 1, 5, 1);
        jSpinner1and5horurs.setModel(model);
    }

private void loadPhotographersCombo() {
       
        jComboBox1photographerlist.setEnabled(false);
        jComboBox1photographerlist.removeAllItems();
        jComboBox1photographerlist.addItem("Loading...");


        new Thread(new Runnable() {
            @Override
            public void run() {
               
                photographersList = controller.getPhotographers();

                javax.swing.SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        jComboBox1photographerlist.removeAllItems();
                        
                        if (photographersList.isEmpty()) {
                            jComboBox1photographerlist.addItem("No photographers found");
                        } else {
                            for (Photographer p : photographersList) {
                                jComboBox1photographerlist.addItem(p.getName());
                            }
                            jComboBox1photographerlist.setEnabled(true); // Habilitar de nuevo
                        }
                    }
                });
            }
        }).start();
    }
    // ---------------------------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmContrat().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1contrat;
    private javax.swing.JButton jButton2mainmenu;
    private javax.swing.JComboBox<String> jComboBox1photographerlist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1and5horurs;
    // End of variables declaration//GEN-END:variables
}
