package view;

import model.Product;
import model.ProductValidator;
import model.TaxCalculator;
import controller.*;

import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.List;

import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Bryan Gudino, KNOWLEDGE ENCAPSULATE, @ESPE
 */
public class FrmAddProduct extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAddProduct.class.getName());

    private static java.util.List<Product> productList = new java.util.ArrayList<>();
    
    public static java.util.List<Product> getProductList() {
    return productList;
    }
    
    /**
     * Creates new form FrmAddProduct
     */
    public FrmAddProduct() {
        initComponents();
        
        lblPriceWithVAT.setEditable(false);

        enableAutoVATCalculation();
        
    }
    
/////////////////    
    
private void enableAutoVATCalculation() {

    lblBasePrice.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {

        private void calculate() {
            String priceText = lblBasePrice.getText().trim();

            if (priceText.isEmpty()) {
                lblPriceWithVAT.setText("");
                return;
            }

            if (!ProductValidator.isValidBasePrice(priceText)) {
                lblPriceWithVAT.setText("Invalid");
                return;
            }

            double basePrice = ProductValidator.parseBasePrice(priceText);
            double priceWithVAT = TaxCalculator.calculatePriceWithVAT(basePrice);

            lblPriceWithVAT.setText(String.format("%.2f", priceWithVAT));
        }

        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) {
            calculate();
        }

        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) {
            calculate();
        }

        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) {
            calculate();
        }
    });
}
////////////////
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAddToList = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtProductName = new javax.swing.JLabel();
        txtBasePrice = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JLabel();
        txtPriceWithVAT = new javax.swing.JLabel();
        lblProductName = new javax.swing.JTextField();
        lblBasePrice = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JTextField();
        lblPriceWithVAT = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProductList = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ADD PRODUCT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnAddToList.setText("Add to List");
        btnAddToList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToListActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(btnAddToList)
                .addGap(72, 72, 72)
                .addComponent(btnClear)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddToList)
                    .addComponent(btnClear))
                .addContainerGap())
        );

        txtProductName.setText("Product Name:");

        txtBasePrice.setText("Base Price ($):");

        txtQuantity.setText("Quantity (Stock):");

        txtPriceWithVAT.setText("Price with VAT:");

        lblBasePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblBasePriceActionPerformed(evt);
            }
        });
        lblBasePrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblBasePriceKeyReleased(evt);
            }
        });

        lblQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblQuantityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProductName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBasePrice, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPriceWithVAT, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPriceWithVAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductName)
                    .addComponent(lblBasePrice)
                    .addComponent(lblQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProductName)
                    .addComponent(lblProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBasePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBasePrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPriceWithVAT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPriceWithVAT))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        menuProductList.setText("Product List");
        menuProductList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuProductListMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuProductList);

        menuExit.setText("Exit");
        jMenuBar1.add(menuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToListActionPerformed

//        Product product = new Product(
//        lblProductName.getText().trim(),
//        lblBasePrice,
//        lblQuantity,
//        lblPriceWithVAT
//    );
//
//    ProductController controller = new ProductController();
//    controller.saveProduct(product);   // ⬅ guarda UNO
//    controller.closeConnection();
//
//    JOptionPane.showMessageDialog(this, "Product saved successfully");
//
//    this.dispose();
//
//        

   // 1. Nombre
    String name = lblProductName.getText().trim();

    // 2. Precio base (coma o punto)
    double basePrice = Double.parseDouble(
        lblBasePrice.getText().replace(",", ".")
    );

    // 3. Precio con IVA
    double priceWithVAT = Double.parseDouble(
        lblPriceWithVAT.getText().replace(",", ".")
    );

    // 4. Stock
    int stock = Integer.parseInt(
        lblQuantity.getText().trim()
    );

    // 5. Crear producto
    Product product = new Product(
        name,
        basePrice,
        priceWithVAT,
        stock
    );

    // 6. Guardar en Mongo
    ProductController controller = new ProductController();
    controller.saveProduct(product);
    controller.closeConnection();

    JOptionPane.showMessageDialog(this, "Product saved successfully");

    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddToListActionPerformed

    private void lblQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblQuantityActionPerformed

    private void menuProductListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuProductListMouseClicked

    FrmProductList frmProductList = new FrmProductList();
    frmProductList.setVisible(true);
    this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuProductListMouseClicked

    private void lblBasePriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblBasePriceKeyReleased
        
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBasePriceKeyReleased

    private void lblBasePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblBasePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBasePriceActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

    lblProductName.setText("");
    lblBasePrice.setText("");
    lblQuantity.setText("");
    lblPriceWithVAT.setText("");
    
    // Opcional: regresar foco al primer campo
    lblProductName.requestFocus();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAddProduct().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToList;
    private javax.swing.JButton btnClear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lblBasePrice;
    private javax.swing.JTextField lblPriceWithVAT;
    private javax.swing.JTextField lblProductName;
    private javax.swing.JTextField lblQuantity;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenu menuProductList;
    private javax.swing.JLabel txtBasePrice;
    private javax.swing.JLabel txtPriceWithVAT;
    private javax.swing.JLabel txtProductName;
    private javax.swing.JLabel txtQuantity;
    // End of variables declaration//GEN-END:variables
}
