package view;

import javax.swing.table.DefaultTableModel;
import java.util.List;
import model.*; 
import controller.ProductController;
import view.FrmAddProduct; 

import javax.swing.JOptionPane;



/**
 *
 * @author Bryan Gudino, KNOWLEDGE ENCAPSULATE, @ESPE
 */
public class FrmProductList extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmProductList.class.getName());
    
    private final ProductManager productManager = new ProductManager();    
    
    private final ProductController productController = new ProductController();

    /**
     * Creates new form FrmProductList
     */
    public FrmProductList() {
        initComponents();
        loadProducts();
        
        initActions();
        
        tblProducts.getSelectionModel().addListSelectionListener(event -> {
        if (!event.getValueIsAdjusting()) { //double push
            updateSpinnerMax();
        }
        });
        
        btnModifyProduct.addActionListener(evt -> btnModifyProductActionPerformed(evt));

        btnDeleteProduct.addActionListener(evt -> {
    int selectedRow = tblProducts.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select a product first");
        return;
    }

    Product product = productController.getProductsFromDB().get(selectedRow);

    // -VAT
    double savedVAT = Double.parseDouble(lblSavedVAT.getText().replace("$", "").trim());
    savedVAT -= product.getVatAccumulated();
    if (savedVAT < 0) savedVAT = 0; // no permitir negativo
    lblSavedVAT.setText(String.format("$ %.2f", savedVAT));

    // Delete list
    productController.getProductsFromDB().remove(selectedRow);

    // Refresh
    loadProducts();
});

    btnRefresh.addActionListener(evt -> refreshProductsTable());
    
    }
    
//////////////////////////////    
private void initActions() {
    cmbAction.removeAllItems();
    cmbAction.addItem("Sell");
    cmbAction.addItem("Donate");
    cmbAction.addItem("Discontinue");
}   
/////////////////////////////

private void updateSpinnerMax() {
    int selectedRow = tblProducts.getSelectedRow();
    if (selectedRow == -1) {
        spnQuantityToSell.setModel(new javax.swing.SpinnerNumberModel(1, 1, 1, 1));
        return;
    }

    // Stock selected
    int stock = Integer.parseInt(tblProducts.getValueAt(selectedRow, 3).toString());

    // Config. spinner
    spnQuantityToSell.setModel(new javax.swing.SpinnerNumberModel(1, 1, stock, 1));
}

////////////////////////
    public void loadProducts() {
//    java.util.List<Product> products = FrmAddProduct.getProductList(); // <--- lee la lista
//
//    DefaultTableModel model = new DefaultTableModel();
//    model.setColumnIdentifiers(new String[]{"Product Name", "Base Price", "Price with VAT", "Stock"});
//
//    for (Product p : products) {
//        model.addRow(new Object[]{
//            p.getName(),
//            String.format("%.2f", p.getBasePrice()),
//            String.format("%.2f", p.getPriceWithVAT()),
//            p.getStock()
//        });
//    }
//
//    tblProducts.setModel(model); 


}
///////////////////
   
    ///  
private void refreshProductsTable() {
    List<Product> products = productController.getProductsFromDB();

    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{"Product Name", "Base Price", "Price with VAT", "Stock"});

    for (Product p : products) {
        model.addRow(new Object[]{
            p.getName(),
            String.format("%.2f", p.getBasePrice()),
            String.format("%.2f", p.getPriceWithVAT()),
            p.getStock()
        });
    }

    tblProducts.setModel(model);
}

    ///
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        btnModifyProduct = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        scrProducts = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        txtAction = new javax.swing.JLabel();
        cmbAction = new javax.swing.JComboBox<>();
        spnQuantityToSell = new javax.swing.JSpinner();
        txtQuantityToSell = new javax.swing.JLabel();
        btnApplyAction = new javax.swing.JButton();
        txtSavedVAT = new javax.swing.JLabel();
        lblSavedVAT = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAddProduct = new javax.swing.JMenu();
        menuExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PRODUCT LIST");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel1)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDeleteProduct.setText("Delete Product");
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });

        btnModifyProduct.setText("Modify Product");
        btnModifyProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnModifyProduct)
                .addGap(29, 29, 29)
                .addComponent(btnDeleteProduct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addGap(141, 141, 141))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh)
                    .addComponent(btnSave)
                    .addComponent(btnDeleteProduct)
                    .addComponent(btnModifyProduct))
                .addContainerGap())
        );

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product Name", "Price VAT", "Stock", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrProducts.setViewportView(tblProducts);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrProducts)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        txtAction.setText("Action:");

        cmbAction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sell", "Donate", "Discontinue" }));

        txtQuantityToSell.setText("Quantity to Sell:");

        btnApplyAction.setText("Apply Action");
        btnApplyAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionActionPerformed(evt);
            }
        });

        txtSavedVAT.setText("Saved VAT:");

        lblSavedVAT.setText("$ 0.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSavedVAT)
                    .addComponent(txtAction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cmbAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(txtQuantityToSell)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnQuantityToSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnApplyAction))
                    .addComponent(lblSavedVAT, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAction)
                    .addComponent(cmbAction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnQuantityToSell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantityToSell)
                    .addComponent(btnApplyAction))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSavedVAT)
                    .addComponent(lblSavedVAT))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuAddProduct.setText("Add Product");
        menuAddProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAddProductMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAddProduct);

        menuExit.setText("Exit");
        jMenuBar1.add(menuExit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    int selectedRow = tblProducts.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select a product first");
        return;
    }

    Product product = productController.getProductsFromDB().get(selectedRow);
    String action = (String) cmbAction.getSelectedItem();
    int qty = (int) spnQuantityToSell.getValue();

    if (qty > product.getStock()) {
        JOptionPane.showMessageDialog(this, "Not enough stock");
        return;
    }

    switch (action) {
        case "Sell":
            product.setStock(product.getStock() - qty);
            double savedVAT = Double.parseDouble(lblSavedVAT.getText().replace("$", "").trim());
            savedVAT += TaxCalculator.calculateVAT(product.getBasePrice() * qty);
            lblSavedVAT.setText(String.format("$ %.2f", savedVAT));
            break;
        case "Donate":
        case "Discontinue":
            product.setStock(product.getStock() - qty);
            break;
    }

    // Guarda cambios en MongoDB
    productController.saveOrUpdateProduct(product);

    refreshProductsTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void menuAddProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAddProductMouseClicked

    FrmAddProduct frmAddProduct = new FrmAddProduct();
    frmAddProduct.setVisible(true);
    this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAddProductMouseClicked

    private void btnApplyActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionActionPerformed

       int selectedRow = tblProducts.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Select a product first");
        return;
    }

    // 🔥 PRODUCTO DESDE MONGO
    Product product = productController.getProductsFromDB().get(selectedRow);

    String action = (String) cmbAction.getSelectedItem();
    int qty = (int) spnQuantityToSell.getValue();

    if (qty > product.getStock()) {
        JOptionPane.showMessageDialog(this, "Not enough stock");
        return;
    }

    double vat = 0;

    switch (action) {
        case "Sell":
            product.setStock(product.getStock() - qty);  // 🔹 Disminuye stock
            vat = TaxCalculator.calculateVAT(product.getBasePrice() * qty);
            product.addVatAccumulated(vat);

            // Actualizar Saved VAT en GUI
            double savedVAT = Double.parseDouble(lblSavedVAT.getText().replace("$", "").trim());
            savedVAT += vat;
            lblSavedVAT.setText(String.format("$ %.2f", savedVAT));
            break;

        case "Donate":
        case "Discontinue":
            product.setStock(product.getStock() - qty); // 🔹 Disminuye stock
            break;

        default:
            JOptionPane.showMessageDialog(this, "Action cancelled");
            return;
    }

    // 🔹 Guardar cambios en MongoDB
    productController.saveOrUpdateProduct(product);

    // 🔹 Refrescar tabla para mostrar stock actualizado
    refreshProductsTable();    
        // TODO add your handling code here:
    }//GEN-LAST:event_btnApplyActionActionPerformed

    private void btnModifyProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyProductActionPerformed

int selectedRow = tblProducts.getSelectedRow();
if (selectedRow == -1) return;

Product product = productController.getProductsFromDB().get(selectedRow);

// Pedir nuevos valores
String newName = JOptionPane.showInputDialog(this, "Enter new name:", product.getName());
if (newName == null || newName.trim().isEmpty()) return;

String priceStr = JOptionPane.showInputDialog(this, "Enter new base price:", product.getBasePrice());
if (priceStr == null) return;

String stockStr = JOptionPane.showInputDialog(this, "Enter new stock:", product.getStock());
if (stockStr == null) return;

try {
    product.setName(newName);
    product.setBasePrice(Double.parseDouble(priceStr));
    product.setStock(Integer.parseInt(stockStr));
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Invalid values");
    return;
}

// Guardar cambios en MongoDB
productController.saveOrUpdateProduct(product);

// Refrescar tabla
refreshProductsTable();
JOptionPane.showMessageDialog(this, "Product updated successfully!");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifyProductActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed

        
        
        refreshProductsTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed

int selectedRow = tblProducts.getSelectedRow();
if (selectedRow == -1) return;

Product product = productController.getProductsFromDB().get(selectedRow);
int confirm = JOptionPane.showConfirmDialog(this,
        "Delete product " + product.getName() + "?",
        "Confirm",
        JOptionPane.YES_NO_OPTION);

if (confirm == JOptionPane.YES_OPTION) {
    productController.deleteProduct(product);
    refreshProductsTable();
}

        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmProductList().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApplyAction;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnModifyProduct;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbAction;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblSavedVAT;
    private javax.swing.JMenu menuAddProduct;
    private javax.swing.JMenu menuExit;
    private javax.swing.JScrollPane scrProducts;
    private javax.swing.JSpinner spnQuantityToSell;
    private javax.swing.JTable tblProducts;
    private javax.swing.JLabel txtAction;
    private javax.swing.JLabel txtQuantityToSell;
    private javax.swing.JLabel txtSavedVAT;
    // End of variables declaration//GEN-END:variables
}
