package ec.edu.espe.contactsbook.view;

<<<<<<< HEAD
import ec.edu.espe.contactsbook.model.Contact;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import java.awt.HeadlessException;
import org.bson.Document;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.ParseException;
=======
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import ec.edu.espe.contactsbook.model.Contact;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
import org.bson.types.ObjectId;
import java.awt.HeadlessException;
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8

/**
 *
 * @author Arelys Otavalo, The POOwer Rangers of Programming,@espe
 */
public class FrmContacts extends javax.swing.JFrame {

<<<<<<< HEAD
    Contact contact = new Contact();
    private MongoCollection<Document> contactsCollection;

    public FrmContacts() {
        initComponents();
        connectToMongoDB();
=======
    private Document loadedContactDocument = null;
    private ButtonGroup sexGroup;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch;
    private ObjectId selectedId;
    private Contact contact = new Contact();
    private MongoCollection<Document> contactsCollection;

    public FrmContacts() {
        sexGroup = new ButtonGroup();
        initComponents();
        sexGroup.add(radSexMale);
        sexGroup.add(radSexFemale);
        connectToMongoDB();
        emptyFields();
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        btnSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchInputActionPerformed(evt);
            }
        });
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< HEAD
=======
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        ftdBirthDate = new javax.swing.JFormattedTextField();
        cmbType = new javax.swing.JComboBox<>();
        radSexMale = new javax.swing.JRadioButton();
        radSexFemale = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstHobbies = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaComments = new javax.swing.JTextArea();
<<<<<<< HEAD
        jPanel3 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
=======
        btnSave = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtSearchInput = new javax.swing.JTextField();
        btnSearchButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableResults = new javax.swing.JTable();
        btnLoad = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("CONTACTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
<<<<<<< HEAD
                .addContainerGap(18, Short.MAX_VALUE))
=======
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
        );

        jLabel2.setText("id:");

        jLabel3.setText("First Name:");

        jLabel4.setText("Last Name:");

        jLabel5.setText("Age:");

        jLabel6.setText("Birth Date:");

        jLabel7.setText("Type:");

        jLabel8.setText("Sex:");

        jLabel9.setText("Hobbies:");

        jLabel10.setText("Comments:");

        txtFirstName.setToolTipText("Only the first name is accepted");

        ftdBirthDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        ftdBirthDate.setToolTipText("The format to the Date is m/d/a");

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Family", "Friend", "Job", "Unknown" }));

        radSexMale.setText("Male");
        radSexMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSexMaleActionPerformed(evt);
            }
        });

        radSexFemale.setText("Female");

        lstHobbies.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Play Soccer", "Djing", "Read", "Cook", "Swim", "Sing", "Play an instrument" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstHobbies);

        txaComments.setColumns(20);
        txaComments.setRows(5);
        jScrollPane2.setViewportView(txaComments);

<<<<<<< HEAD
=======
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ftdBirthDate)
                                .addComponent(txtFirstName)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(radSexMale)
                                .addGap(28, 28, 28)
                                .addComponent(radSexFemale))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
<<<<<<< HEAD
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
=======
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addGap(2, 2, 2)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addGap(28, 28, 28))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(ftdBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
<<<<<<< HEAD
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
=======
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(radSexMale)
                            .addComponent(radSexFemale))
                        .addGap(25, 25, 25)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
<<<<<<< HEAD
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
=======
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnSave)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("Search by id, name or last name");

        txtSearchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchInputActionPerformed(evt);
            }
        });

        btnSearchButton.setText("Search");

        tableResults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Name", "Last Name", "BrithDate", "Age", "Type", "Sex", "Hobbies", "Comments"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableResults);

        btnLoad.setText("Load");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(292, 292, 292)
                .addComponent(btnSave)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
=======
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLoad)
                            .addComponent(btnUpdate)
                            .addComponent(btnSearchButton))
                        .addGap(129, 129, 129))))
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(28, 28, 28)
                .addComponent(btnSave)
                .addContainerGap(49, Short.MAX_VALUE))
=======
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLoad)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)))
                .addContainerGap(23, Short.MAX_VALUE))
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
=======
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
<<<<<<< HEAD
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
=======
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radSexMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSexMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radSexMaleActionPerformed

<<<<<<< HEAD
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (contactsCollection == null) {
            JOptionPane.showMessageDialog(rootPane, "There isn't connection to the database", "Save Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int option;
        readValues();
        option = JOptionPane.showConfirmDialog(rootPane, "saving contacts -->" + contact, "SAVE CONTACTS?", JOptionPane.YES_NO_CANCEL_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            
            try {
                // change String to an Objetc Date to upload this information too mongo
                SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yy");
                Date birthDate = null;
=======
    private void selectHobbiesInList(javax.swing.JList<String> list, List<String> hobbiesToSelect) {
        if (hobbiesToSelect == null || hobbiesToSelect.isEmpty()) {
            list.clearSelection();
            return;
        }
        javax.swing.ListModel<String> model = list.getModel();
        ArrayList<Integer> indices = new ArrayList<>();
        for (int i = 0; i < model.getSize(); i++) {
            String item = model.getElementAt(i);
            if (hobbiesToSelect.contains(item)) {
                indices.add(i);
            }
        }
        int[] selectedIndices = indices.stream().mapToInt(i -> i).toArray();
        list.setSelectedIndices(selectedIndices);
    }

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = tableResults.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(rootPane, "You must select a row in the table.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ObjectId idToLoad = (ObjectId) tableResults.getModel().getValueAt(selectedRow, 0);

        try {
            Document contactDoc = contactsCollection.find(new Document("_id", idToLoad)).first();

            if (contactDoc != null) {
                selectedId = idToLoad;

                txtFirstName.setText(contactDoc.getString("firstName"));
                txtLastName.setText(contactDoc.getString("lastName"));

                Date birthDate = contactDoc.getDate("birthDate");
                if (birthDate != null) {
                    ftdBirthDate.setText(new SimpleDateFormat("MM/dd/yy").format(birthDate));
                } else {
                    ftdBirthDate.setText("");
                }

                cmbType.setSelectedItem(contactDoc.getString("typeOfContact"));
                String sex = contactDoc.getString("sex");
                if ("Male".equals(sex)) {
                    radSexMale.setSelected(true);
                } else if ("Female".equals(sex)) {
                    radSexFemale.setSelected(true);
                } else {
                }
                List<String> hobbiesList = contactDoc.getList("hobbies", String.class, Collections.emptyList());
                selectHobbiesInList(lstHobbies, hobbiesList);
                txaComments.setText(contactDoc.getString("comments"));

                JOptionPane.showMessageDialog(rootPane, "Contact loaded ready for editing.", "Successful Load", JOptionPane.INFORMATION_MESSAGE);

            } else {
                JOptionPane.showMessageDialog(rootPane, "Load Error: Contact not found in DB.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error loading contact: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (contactsCollection == null) {
            JOptionPane.showMessageDialog(rootPane,
                    "There isn't connection to the database",
                    "Save Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        readValues();
        int option = JOptionPane.showConfirmDialog(
                rootPane,
                "saving contact --> " + contact,
                "SAVE CONTACT?",
                JOptionPane.YES_NO_CANCEL_OPTION
        );

        if (option == JOptionPane.YES_OPTION) {

            try {
                SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yy");
                Date birthDate = null;

>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
                try {
                    String dateString = ftdBirthDate.getText();
                    if (dateString != null && !dateString.trim().isEmpty()) {
                        birthDate = dateFormat.parse(dateString);
                    }
                } catch (ParseException e) {
<<<<<<< HEAD
                    JOptionPane.showMessageDialog(rootPane, "Invalid date of birth format. Saving without date of birth.", "Warning about date", JOptionPane.WARNING_MESSAGE);
                }

                // Create the document in mongoDb
=======
                    JOptionPane.showMessageDialog(
                            rootPane,
                            "Invalid date of birth format. Saving without date of birth.",
                            "Warning about date",
                            JOptionPane.WARNING_MESSAGE
                    );
                }
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
                Document contactDoc = new Document("firstName", contact.getFirstName())
                        .append("lastName", contact.getLastName())
                        .append("age", contact.getAge())
                        .append("birthDate", birthDate)
                        .append("typeOfContact", contact.getTypeOfContact())
                        .append("sex", contact.getSex())
                        .append("hobbies", contact.getHobbies())
                        .append("comments", contact.getComments());

<<<<<<< HEAD
                // Insert data to the collection
                contactsCollection.insertOne(contactDoc);

                JOptionPane.showMessageDialog(rootPane, "Contact saved successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                emptyFields();
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(rootPane, "Error saving to MongoDB " + e.getMessage(), "Save errir", JOptionPane.ERROR_MESSAGE);
            }

        } else if (option == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(rootPane, "your date will be lost -->", "", JOptionPane.WARNING_MESSAGE);
=======
                contactsCollection.insertOne(contactDoc);
                JOptionPane.showMessageDialog(
                        rootPane,
                        "Contact saved successfully",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE
                );
                emptyFields();
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(
                        rootPane,
                        "Error saving to MongoDB: " + e.getMessage(),
                        "Save Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        } else if (option == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(
                    rootPane,
                    "Your data will be lost.",
                    "",
                    JOptionPane.WARNING_MESSAGE
            );
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
            emptyFields();
        } else {
            txtFirstName.requestFocus();
        }
<<<<<<< HEAD

    }//GEN-LAST:event_btnSaveActionPerformed
=======
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSearchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchInputActionPerformed
        if (contactsCollection == null) {
            JOptionPane.showMessageDialog(rootPane, "No connection to the database.", "Search Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String searchText = txtSearchInput.getText().trim();
        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Enter an ID, first name or last name to search.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Document query;

        if (ObjectId.isValid(searchText)) {
            query = new Document("_id", new ObjectId(searchText));
        } else {
            Pattern regex = Pattern.compile(searchText, Pattern.CASE_INSENSITIVE);
            query = new Document("$or", Arrays.asList(
                    new Document("firstName", new Document("$regex", regex)),
                    new Document("lastName", new Document("$regex", regex))
            ));
        }

        DefaultTableModel model = (DefaultTableModel) tableResults.getModel();
        model.setRowCount(0);

        try (MongoCursor<Document> cursor = contactsCollection.find(query).iterator()) {
            while (cursor.hasNext()) {
                Document doc = cursor.next();

                Object birthDateObj = doc.get("birthDate");
                String birthDateStr = "";
                if (birthDateObj instanceof Date) {
                    birthDateStr = new SimpleDateFormat("MM/dd/yy").format((Date) birthDateObj);
                }

                List<String> hobbiesList = doc.getList("hobbies", String.class, Collections.emptyList());
                String hobbiesStr = String.join(", ", hobbiesList);

                model.addRow(new Object[]{
                    doc.getObjectId("_id"),
                    doc.getString("firstName"),
                    doc.getString("lastName"),
                    birthDateStr,
                    doc.getInteger("age", 0),
                    doc.getString("typeOfContact"),
                    doc.getString("sex"),
                    hobbiesStr,
                    doc.getString("comments")
                });
            }
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(rootPane, "No contacts found.", "No Results", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Search error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtSearchInputActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (contactsCollection == null) {
            JOptionPane.showMessageDialog(rootPane,
                    "There isn't connection to the database",
                    "Update Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (selectedId == null) {
            JOptionPane.showMessageDialog(rootPane,
                    "You must first select a contact to update",
                    "No Contact Selected",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        contact = null;
        readValues();
        if (contact == null) {
            return;
        }

        int option = JOptionPane.showConfirmDialog(
                rootPane,
                "Updating contact --> " + contact.getFirstName() + " " + contact.getLastName(),
                "UPDATE CONTACT?",
                JOptionPane.YES_NO_CANCEL_OPTION
        );

        if (option == JOptionPane.YES_OPTION) {
            try {
                SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yy");
                Date birthDate = null;

                try {
                    String dateString = ftdBirthDate.getText();
                    if (dateString != null && !dateString.trim().isEmpty()) {
                        birthDate = dateFormat.parse(dateString);
                    }
                } catch (ParseException e) {
                    JOptionPane.showMessageDialog(rootPane,
                            "Invalid date format. Updating without date.",
                            "Warning",
                            JOptionPane.WARNING_MESSAGE);
                }

                Document updatedDoc = contactToDocument(contact, birthDate);
                contactsCollection.updateOne(
                        new Document("_id", selectedId),
                        new Document("$set", updatedDoc)
                );
                JOptionPane.showMessageDialog(rootPane,
                        "Contact updated successfully",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                emptyFields();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,
                        "Error updating contact: " + e.getMessage(),
                        "Update Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else if (option == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(rootPane,
                    "Update canceled",
                    "",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            txtFirstName.requestFocus();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
    private void connectToMongoDB() {
        try {
            String connectionString = "mongodb+srv://Arelys:Arelys1234@cluster0.3u6ujwz.mongodb.net/Contacts?retryWrites=true&w=majority";
            MongoClient mongoClient = MongoClients.create(connectionString);
            MongoDatabase database = mongoClient.getDatabase("Contacts");
            contactsCollection = database.getCollection("ContactsBook");
            System.out.println("Succesfully conection");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error connecting to MongoDB " + e.getMessage(), "Conexion error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void emptyFields() {
        txtFirstName.setText("");
        txtLastName.setText("");
        ftdBirthDate.setText("");
<<<<<<< HEAD
        cmbType.setSelectedIndex(0);
        radSexFemale.setSelected(true);
        lstHobbies.clearSelection();
        txaComments.setText("");
=======
        txaComments.setText("");
        cmbType.setSelectedIndex(0);
        if (sexGroup != null) {
            sexGroup.clearSelection();
        }
        lstHobbies.clearSelection();
        txtSearchInput.setText("");
        selectedId = null;
        DefaultTableModel model = (DefaultTableModel) tableResults.getModel();
        model.setRowCount(0);
        txtFirstName.requestFocus();
    }

    private Document contactToDocument(Contact c, Date birthDate) {
        return new Document("firstName", c.getFirstName())
                .append("lastName", c.getLastName())
                .append("age", c.getAge())
                .append("birthDate", birthDate)
                .append("typeOfContact", c.getTypeOfContact())
                .append("sex", c.getSex())
                .append("hobbies", c.getHobbies())
                .append("comments", c.getComments());
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
    }

    private void readValues() {
        String firstName;
        String lastName;
        int age;
<<<<<<< HEAD
        String typeOfContact; //Family, Friend,Job,Unknown
        String sex; //male, female
        ArrayList<String> hobbies = new ArrayList<>();
        String comments;

        firstName = txtFirstName.getText();
        lastName = txtLastName.getText();
        //TODO compute age based on BirthDay
        age = 20;
        typeOfContact = cmbType.getSelectedItem().toString();
        //TODO code we use the radio buttons to initializa the sex
        sex = "Female";
        //cfode a loop to add all the hobbies
        hobbies.add(lstHobbies.getSelectedValue());
        comments = txaComments.getText();

        contact = new Contact(age, firstName, lastName, age, typeOfContact, sex, hobbies, comments);
=======
        String typeOfContact;
        String sex;
        ArrayList<String> hobbies = new ArrayList<>();
        String comments;

        firstName = txtFirstName.getText().trim();
        lastName = txtLastName.getText().trim();

        String nameRegex = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$";

        if (firstName.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "The First Name field cannot be empty.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            txtFirstName.requestFocus();
            return;
        }
        if (!firstName.matches(nameRegex)) {
            JOptionPane.showMessageDialog(rootPane, "The First Name can only contain letters, accents, Ñ and spaces.", "Format Error", JOptionPane.ERROR_MESSAGE);
            txtFirstName.requestFocus();
            return;
        }
        if (lastName.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "The Last Name field cannot be empty.", "Validation Error", JOptionPane.ERROR_MESSAGE);
            txtLastName.requestFocus();
            return;
        }
        if (!lastName.matches(nameRegex)) {
            JOptionPane.showMessageDialog(rootPane, "The Last Name can only contain letters, accents, Ñ and spaces.", "Format Error", JOptionPane.ERROR_MESSAGE);
            txtLastName.requestFocus();
            return;
        }

        try {
            age = 0;
        } catch (NumberFormatException e) {
            age = 19;
        }
        typeOfContact = cmbType.getSelectedItem().toString();

        if (radSexMale.isSelected()) {
            sex = "Male";
        } else if (radSexFemale.isSelected()) {
            sex = "Female";
        } else {
            sex = "Unknown";
        }

        for (String hobby : lstHobbies.getSelectedValuesList()) {
            hobbies.add(hobby);
        }
        comments = txaComments.getText();

        contact = new Contact(age, firstName, lastName, typeOfContact, sex, hobbies, comments);
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmContacts().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JButton btnSave;
=======
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchButton;
    private javax.swing.JButton btnUpdate;
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JFormattedTextField ftdBirthDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
<<<<<<< HEAD
=======
    private javax.swing.JLabel jLabel11;
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
<<<<<<< HEAD
    private javax.swing.JList<String> lstHobbies;
    private javax.swing.JRadioButton radSexFemale;
    private javax.swing.JRadioButton radSexMale;
    private javax.swing.JTextArea txaComments;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
=======
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JList<String> lstHobbies;
    private javax.swing.JRadioButton radSexFemale;
    private javax.swing.JRadioButton radSexMale;
    private javax.swing.JTable tableResults;
    private javax.swing.JTextArea txaComments;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSearchInput;
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
    // End of variables declaration//GEN-END:variables
}
