package ec.espe.edu.contactsbook.view;
<<<<<<< HEAD
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;
import java.time.LocalDate; 
import java.time.Period;    
import java.time.ZoneId;
import javax.swing.JOptionPane;
import ec.edu.espe.contactsbook.model.Contact;
import ec.espe.edu.contactsbook.model.MongoConection;
import java.util.ArrayList;
=======

import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import org.bson.Document;
import javax.swing.JOptionPane;
import ec.edu.espe.contactsbook.model.Contact;
import ec.espe.edu.contactsbook.model.MongoConection;
import java.awt.Color;
import java.util.ArrayList;

>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
/**
 *
 * @author Mathews Pastor, The POOwer Rangers Of Programming
 */
public class FrmContacts extends javax.swing.JFrame {
<<<<<<< HEAD
    
=======

>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
    Contact contact = new Contact();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmContacts.class.getName());

    /**
     * Creates new form FrmContacts
     */
    public FrmContacts() {
        initComponents();
<<<<<<< HEAD
=======

        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
<<<<<<< HEAD
=======
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
<<<<<<< HEAD
        jLabel7 = new javax.swing.JLabel();
=======
        lblType = new javax.swing.JLabel();
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
        cmbType = new javax.swing.JComboBox<>();
        Calendar = new com.toedter.calendar.JCalendar();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        radSexMale = new javax.swing.JRadioButton();
        radSexFemale = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstHobbies = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextArea();
        txtAge = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 2, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setText("CONTACTS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(349, 349, 349))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        btnAdd.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 51, 153));
        btnAdd.setText("SAVE");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

<<<<<<< HEAD
=======
        btnDelete.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 53, 153));
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 51, 153));
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 51, 153));
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(0, 51, 153));
        btnCancel.setText("CANCEL");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(380, 380, 380)
                .addComponent(btnAdd)
=======
                .addGap(124, 124, 124)
                .addComponent(btnAdd)
                .addGap(40, 40, 40)
                .addComponent(btnCancel)
                .addGap(136, 136, 136)
                .addComponent(btnDelete)
                .addGap(33, 33, 33)
                .addComponent(btnSearch)
                .addGap(37, 37, 37)
                .addComponent(btnUpdate)
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(23, 23, 23)
                .addComponent(btnAdd)
=======
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnSearch)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnCancel))
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("id:");

        jLabel3.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("First Name:");

        jLabel4.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Last Name:");

        jLabel5.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("Birth Day:");

        jLabel6.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("Age:");

<<<<<<< HEAD
        jLabel7.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Type:");

        cmbType.setBackground(new java.awt.Color(204, 255, 255));
        cmbType.setForeground(new java.awt.Color(0, 0, 102));
        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Family", "Friend", "Job", "Unknown" }));
=======
        lblType.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        lblType.setForeground(new java.awt.Color(0, 0, 153));
        lblType.setText("Type:");

        cmbType.setBackground(new java.awt.Color(204, 255, 255));
        cmbType.setForeground(new java.awt.Color(0, 0, 102));
        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Family", "Friend", "Job", "Unknown" }));
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8

        Calendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CalendarPropertyChange(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Hobbies:");

        jLabel10.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("Sex:");

        radSexMale.setForeground(new java.awt.Color(0, 0, 204));
        radSexMale.setText("Male");
        radSexMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSexMaleActionPerformed(evt);
            }
        });

        radSexFemale.setForeground(new java.awt.Color(0, 0, 204));
        radSexFemale.setText("Female");
        radSexFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSexFemaleActionPerformed(evt);
            }
        });

        lstHobbies.setBackground(new java.awt.Color(204, 255, 255));
        lstHobbies.setForeground(new java.awt.Color(0, 0, 153));
        lstHobbies.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Play Soccer", "Djing", "Read", "Cook", "Swim", "Sing", "Play an instrument" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstHobbies);

        jLabel11.setFont(new java.awt.Font("Footlight MT Light", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));
        jLabel11.setText("Comments:");

        txtComments.setColumns(20);
        txtComments.setRows(5);
        jScrollPane2.setViewportView(txtComments);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Calendar, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                            .addComponent(txtLastName)
                                            .addComponent(txtFirstName))
                                        .addGap(162, 162, 162)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
=======
                                            .addComponent(lblType, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(radSexMale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(38, 38, 38)
                                        .addComponent(radSexFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1))
                                .addGap(111, 111, 111))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAge)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
<<<<<<< HEAD
                            .addComponent(jLabel7)
=======
                            .addComponent(lblType)
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
                            .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(radSexMale)
                                    .addComponent(radSexFemale)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radSexMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSexMaleActionPerformed
        if (radSexMale.isSelected()) {
            radSexFemale.setEnabled(false);
        } else {
            radSexFemale.setEnabled(true);
        }
    }//GEN-LAST:event_radSexMaleActionPerformed

    private void radSexFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSexFemaleActionPerformed
        if (radSexFemale.isSelected()) {
            radSexMale.setEnabled(false);
        } else {
            radSexMale.setEnabled(true);
        }
    }//GEN-LAST:event_radSexFemaleActionPerformed

    private void CalendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CalendarPropertyChange
        if ("calendar".equals(evt.getPropertyName())) {
            int age = calculateAge(Calendar.getDate());
<<<<<<< HEAD
            txtAge.setText(String.valueOf(age)); 
=======
            txtAge.setText(String.valueOf(age));
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
        }
    }//GEN-LAST:event_CalendarPropertyChange

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
<<<<<<< HEAD
        contact = readValues();
        int option;
        option = JOptionPane.showConfirmDialog(rootPane, "saving contacts --> " + contact, "SAVE CONTACTS?", JOptionPane.YES_NO_CANCEL_OPTION);  
        if(option == JOptionPane.YES_OPTION){
            try {
                MongoDatabase database = MongoConection.getDatabase();
                MongoCollection<Document> collection = database.getCollection("Contact");
                     Document doc = new Document("id", contact.getId())
                    .append("firstName", contact.getFirstName())
                    .append("lastName", contact.getLastName())
                    .append("age", contact.getAge())
                    .append("typeOfContact", contact.getTypeOfContact())
                    .append("sex", contact.getSex())
                    .append("hobbies", contact.getHobbies())
                    .append("comments", contact.getComments());
            collection.insertOne(doc);
                JOptionPane.showMessageDialog(rootPane, "YOUR CONTACT IS SAVEED");
                emptyFields();

            } catch (Exception e) {
                System.err.println("Error " + e.getMessage());
            }

        } else if (option == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(rootPane, "YOUR DATE WILL BE LOST","",JOptionPane.WARNING_MESSAGE);
            emptyFields();
        } else {
            txtFirstName.requestFocus();
=======
        if (!validateFields()) {
            return;
        }
        contact = readValues();
        try {
            MongoDatabase database = MongoConection.getDatabase();
            MongoCollection<Document> collection = database.getCollection("Contact");

            Document existingDoc = collection.find(new Document("id", contact.getId())).first();

            if (existingDoc != null) {
                JOptionPane.showMessageDialog(rootPane, "The ID " + contact.getId() + " already exists. Please use a different one.", "", JOptionPane.WARNING_MESSAGE);
                txtId.requestFocus();
                return;
            }

            int option;
            option = JOptionPane.showConfirmDialog(rootPane, "saving contacts --> " + contact, "SAVE CONTACTS?", JOptionPane.YES_NO_CANCEL_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                Document document = new Document("id", contact.getId())
                        .append("firstName", contact.getFirstName())
                        .append("lastName", contact.getLastName())
                        .append("age", contact.getAge())
                        .append("typeOfContact", contact.getTypeOfContact())
                        .append("sex", contact.getSex())
                        .append("hobbies", contact.getHobbies())
                        .append("comments", contact.getComments());
                collection.insertOne(document);
                JOptionPane.showMessageDialog(rootPane, "YOUR CONTACT IS SAVEED");
                emptyFields();
            } else if (option == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(rootPane, "YOUR DATE WILL BE LOST", "", JOptionPane.WARNING_MESSAGE);
                emptyFields();
            } else {
                txtFirstName.requestFocus();
            }
        } catch (Exception e) {
            System.err.println("Error " + e.getMessage());
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

<<<<<<< HEAD
    private int calculateAge(java.util.Date birthDate) {
    if (birthDate == null) {
        return 0; 
    }
    java.time.LocalDate birth = birthDate.toInstant()
        .atZone(java.time.ZoneId.systemDefault())
        .toLocalDate();
    java.time.LocalDate now = java.time.LocalDate.now();
    java.time.Period period = java.time.Period.between(birth, now);
    return period.getYears();
}
    
    private void emptyFields(){
=======
    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (txtId.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "ID is required to search");
            txtId.requestFocus();
            return;
        }

        try {
            MongoDatabase database = MongoConection.getDatabase();
            MongoCollection<Document> collection = database.getCollection("Contact");
            Document doc = collection.find(new Document("id", txtId.getText().trim())).first();

            if (doc != null) {
                txtFirstName.setText(doc.getString("firstName"));
                txtLastName.setText(doc.getString("lastName"));
                txtAge.setText(doc.getString("age"));
                txtComments.setText(doc.getString("comments"));
                cmbType.setSelectedItem(doc.getString("typeOfContact"));
                String sex = doc.getString("sex");
                if ("Male".equals(sex)) {
                    radSexMale.setSelected(true);
                } else if ("Female".equals(sex)) {
                    radSexFemale.setSelected(true);
                }

                txtId.setEditable(false);
                txtId.setBackground(Color.LIGHT_GRAY);
                btnAdd.setEnabled(false);
                btnDelete.setEnabled(true);
                btnUpdate.setEnabled(true);

                JOptionPane.showMessageDialog(rootPane, "CONTACT FOUND");

            } else {
                JOptionPane.showMessageDialog(rootPane, "CONTACT NOT FOUND");
                emptyFields();
            }

        } catch (Exception e) {
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "INSURANCE TO DELETE THE DATA " + txtId.getText()
                + " --> " + txtFirstName.getText() + " " + txtLastName.getText() + " ?", "", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            try {
                MongoDatabase database = MongoConection.getDatabase();
                MongoCollection<Document> collection = database.getCollection("Contact");

                Document result = collection.findOneAndDelete(new Document("id", txtId.getText().trim()));

                if (result != null) {
                    JOptionPane.showMessageDialog(rootPane, "Contact deleted successfully.");
                    emptyFields();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Could not delete. Check if the ID exists.");
                }

            } catch (Exception e) {
                System.err.println("Error deleting: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        contact = readValues();
        int option = JOptionPane.showConfirmDialog(rootPane,
                "¿GUARANTEE TO UPDATE THE DATA " + contact.getFirstName() + "?", "", JOptionPane.YES_NO_OPTION);

        if (option == JOptionPane.YES_OPTION) {
            try {
                MongoDatabase database = MongoConection.getDatabase();
                MongoCollection<Document> collection = database.getCollection("Contact");
                Document filter = new Document("id", txtId.getText());
                Document updateFields = new Document("firstName", contact.getFirstName())
                        .append("lastName", contact.getLastName())
                        .append("age", contact.getAge())
                        .append("typeOfContact", contact.getTypeOfContact())
                        .append("sex", contact.getSex())
                        .append("hobbies", contact.getHobbies())
                        .append("comments", contact.getComments());

                collection.updateOne(filter, new Document("$set", updateFields));

                JOptionPane.showMessageDialog(rootPane, "UPDATED CONTACT INFORMATION");
                emptyFields();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error" + e.getMessage());
            }
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        emptyFields();
    }//GEN-LAST:event_btnCancelActionPerformed

    private int calculateAge(java.util.Date birthDate) {
        if (birthDate == null) {
            return 0;
        }
        java.time.LocalDate birth = birthDate.toInstant()
                .atZone(java.time.ZoneId.systemDefault())
                .toLocalDate();
        java.time.LocalDate now = java.time.LocalDate.now();
        java.time.Period period = java.time.Period.between(birth, now);
        return period.getYears();
    }

    private void emptyFields() {
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
        txtId.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        cmbType.setSelectedIndex(0);
        radSexFemale.setSelected(false);
        radSexMale.setSelected(false);
        lstHobbies.clearSelection();
        txtComments.setText("");
<<<<<<< HEAD
    }
    
    private Contact readValues(){
=======
        txtId.setEditable(true);
        txtId.setBackground(Color.WHITE);
        btnAdd.setEnabled(true);
        btnSearch.setEnabled(true);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
    }

    private Contact readValues() {
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
        String id;
        String firstName;
        String lastName;
        String age;
        String typeOfContact;
<<<<<<< HEAD
        String sex; 
        ArrayList<String> hobbies = new ArrayList<>();
        String comments;
        
=======
        String sex;
        ArrayList<String> hobbies = new ArrayList<>();
        String comments;

>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
        id = txtId.getText();
        firstName = txtFirstName.getText();
        lastName = txtLastName.getText();
        age = txtAge.getText();
        typeOfContact = cmbType.getSelectedItem().toString();
<<<<<<< HEAD
        if(radSexFemale.isSelected() == true) {
=======
        if (radSexFemale.isSelected() == true) {
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
            sex = "Female";
        } else {
            sex = "Male";
        }
<<<<<<< HEAD
        
        hobbies.add(lstHobbies.getSelectedValue());
        comments = txtComments.getText();
        
        contact = new Contact(id, firstName, lastName, age, typeOfContact, sex, hobbies, comments);
        return contact;
    }
=======

        hobbies.add(lstHobbies.getSelectedValue());
        comments = txtComments.getText();

        contact = new Contact(id, firstName, lastName, age, typeOfContact, sex, hobbies, comments);
        return contact;
    }

    private boolean validateFields() {
        if (txtId.getText().trim().isEmpty() || txtFirstName.getText().trim().isEmpty()
                || txtLastName.getText().trim().isEmpty() || !radSexMale.isSelected() && !radSexFemale.isSelected()
                || cmbType.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "DATA INCOMPLETE: YOU MUST COMPLETE THE REQUIRED FIELDS ");
            txtId.setBackground(Color.red);
            txtLastName.setBackground(Color.red);
            txtFirstName.setBackground(Color.red);
            radSexFemale.setForeground(Color.red);
            radSexMale.setForeground(Color.red);
            lblType.setForeground(Color.red);
            return false;
        }
        String namePattern = "^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$";

        if (!txtFirstName.getText().matches(namePattern)) {
            JOptionPane.showMessageDialog(this, "ERROR: The name must only contain letters..");
            txtFirstName.setBackground(Color.red);
            return false;
        }

        if (!txtLastName.getText().matches(namePattern)) {
            JOptionPane.showMessageDialog(this, "ERROR: The last name must only contain letters.");
            txtLastName.setBackground(Color.red);
            return false;
        }
        txtId.setBackground(Color.white);
        txtLastName.setBackground(Color.white);
        txtFirstName.setBackground(Color.white);
        radSexFemale.setForeground(Color.blue);
        radSexMale.setForeground(Color.blue);
        lblType.setForeground(Color.blue);

        return true;
    }

    private boolean validateFieldsSearch() {
        boolean id;
        boolean data;
        id = !txtId.getText().trim().isEmpty();
        data = txtLastName.getText().trim().isEmpty() && txtComments.getText().trim().isEmpty() && txtFirstName.getText().trim().isEmpty();
        if (id && data) {
            txtId.setBackground(Color.white);
            return true;
        } else {
            JOptionPane.showMessageDialog(rootPane, "To SEARCH, please enter ONLY the ID. Clear other text fields.", "", JOptionPane.WARNING_MESSAGE);
            txtId.requestFocus();
            return false;
        }
    }

>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmContacts().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JCalendar Calendar;
    private javax.swing.JButton btnAdd;
<<<<<<< HEAD
=======
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
<<<<<<< HEAD
    private javax.swing.JLabel jLabel7;
=======
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
<<<<<<< HEAD
=======
    private javax.swing.JLabel lblType;
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
    private javax.swing.JList<String> lstHobbies;
    private javax.swing.JRadioButton radSexFemale;
    private javax.swing.JRadioButton radSexMale;
    private javax.swing.JLabel txtAge;
    private javax.swing.JTextArea txtComments;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
