package ec.edu.espe.rentalresidentgui.view;

import ec.edu.espe.rentalresidentgui.controller.ResidentController;
import ec.edu.espe.rentalresidentgui.controller.ParkingSpaceController;
import ec.edu.espe.rentalresidentgui.model.Resident;
import ec.edu.espe.rentalresidentgui.model.Rental;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.util.List;
import org.bson.Document;

/**
 *
 * @author Mateo Aymacaña, T.A.P. (The Art of Programming), @ESPE
 */
public class FrmResidentRental extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmResidentRental.class.getName());

    /**
     * Creates new form FrmResidentRental
     */
    public FrmResidentRental() {
        initComponents();
        loadAvailableSpacesToComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFindResident = new javax.swing.JTextField();
        btnSearchResident = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblSelectedSpace = new javax.swing.JLabel();
        cmbAvailableSpaces = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbMonthsSubscription = new javax.swing.JComboBox<>();
        lblValueToPay = new javax.swing.JLabel();
        lblMonthsOfUse = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnPay = new javax.swing.JButton();
        btnPayAndRenew = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        jLabel1.setText("Resident Rental");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Entry ID:");

        btnSearchResident.setText("Search Resident");
        btnSearchResident.addActionListener(this::btnSearchResidentActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessage)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFindResident, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnSearchResident)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFindResident, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchResident))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMessage)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel3.setText("Value to pay:");

        jLabel4.setText("Months of use:");

        jLabel5.setText("If you wish to renew your subscrption, please fill in the following fields");

        lblSelectedSpace.setText("Available spaces:");

        cmbAvailableSpaces.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AZU-A-03", "AZU-B-02", "CAR-A-04", "CAR-B-03", "CAN-B-03", "CHI-A-03", "CHI-B-02", "COT-B-03", "ORO-A-03", "ORO-B-02", "ESM-B-03" }));
        cmbAvailableSpaces.addActionListener(this::cmbAvailableSpacesActionPerformed);

        jLabel7.setText("Months of subscription:");

        cmbMonthsSubscription.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 to 3 months", "3 to 6 months", "6 to 12 months" }));
        cmbMonthsSubscription.addActionListener(this::cmbMonthsSubscriptionActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblSelectedSpace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbAvailableSpaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbMonthsSubscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 58, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValueToPay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMonthsOfUse)
                        .addGap(197, 197, 197))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lblValueToPay)
                    .addComponent(lblMonthsOfUse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSelectedSpace)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbAvailableSpaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(cmbMonthsSubscription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        btnPay.setText("Pay");
        btnPay.addActionListener(this::btnPayActionPerformed);

        btnPayAndRenew.setText("Pay and Renew");
        btnPayAndRenew.addActionListener(this::btnPayAndRenewActionPerformed);

        btnExit.setText("Exit");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnPay)
                .addGap(116, 116, 116)
                .addComponent(btnPayAndRenew)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(61, 61, 61))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPay)
                    .addComponent(btnPayAndRenew)
                    .addComponent(btnExit))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAvailableSpacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAvailableSpacesActionPerformed
        String selectedSpace = (String) cmbAvailableSpaces.getSelectedItem();

        if (selectedSpace != null && !selectedSpace.equals("Select a space...")) {
            System.out.println("Selected parking space: " + selectedSpace);

            showSpaceDetails(selectedSpace);
        }
    }

    private void showSpaceDetails(String spaceId) {
        lblSelectedSpace.setText("Selected: " + spaceId);

        ParkingSpaceController controller = new ParkingSpaceController();
        Document spaceDetails = controller.getSpaceDetails(spaceId);

        if (spaceDetails != null) {
            String type = spaceDetails.getString("type");
            Boolean isOccupied = spaceDetails.getBoolean("isOccupied");

            String details = "Type: " + type
                    + "\nStatus: " + (isOccupied != null && isOccupied ? "Occupied" : "Available");

            cmbAvailableSpaces.setToolTipText(details);
        }
    }//GEN-LAST:event_cmbAvailableSpacesActionPerformed
    private void loadAvailableSpacesToComboBox() {
        try {
            cmbAvailableSpaces.removeAllItems();

            cmbAvailableSpaces.addItem("Select a space...");

            ParkingSpaceController spaceController = new ParkingSpaceController();
            List<String> availableSpaces = spaceController.getAvailableSpaces();

            for (String space : availableSpaces) {
                cmbAvailableSpaces.addItem(space);
            }

            if (availableSpaces.isEmpty()) {
                cmbAvailableSpaces.addItem("No available spaces");
                cmbAvailableSpaces.setEnabled(false);
                lblMessage.setText("No parking spaces available for rent");
            } else {
                cmbAvailableSpaces.setEnabled(true);
                lblMessage.setText(availableSpaces.size() + " spaces available");
            }

        } catch (Exception e) {
            System.err.println("Error loading spaces to combo box: " + e.getMessage());
            cmbAvailableSpaces.addItem("Error loading spaces");
            cmbAvailableSpaces.setEnabled(false);
        }
    }

    private void refreshAvailableSpaces() {
        loadAvailableSpacesToComboBox();

        int itemCount = cmbAvailableSpaces.getItemCount() - 1;
        if (itemCount > 0) {
            JOptionPane.showMessageDialog(this,
                    "Available spaces list refreshed\n" + itemCount + " spaces available",
                    "Refresh Complete",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void cmbMonthsSubscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMonthsSubscriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMonthsSubscriptionActionPerformed


    private void btnSearchResidentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchResidentActionPerformed

        String input = txtFindResident.getText().trim();

        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please enter an ID or Full Name to search",
                    "Empty Field",
                    JOptionPane.WARNING_MESSAGE);
            txtFindResident.requestFocus();
            lblMessage.setText("");
            return;
        }

        lblMessage.setText("Searching...");
        lblMessage.setForeground(Color.BLUE);

        try {
            ResidentController controller = new ResidentController();
            Resident foundResident = controller.searchResident(input);

            if (foundResident != null) {
                String displayText = foundResident.getName()
                        + " | ID: " + foundResident.getResidentID()
                        + " | Apt: " + foundResident.getApartmentNumber();

                lblMessage.setText(displayText);

                if ("ROTATING".equals(foundResident.getUserType())) {
                    lblMessage.setForeground(new Color(0, 150, 0));
                    lblMessage.setText(lblMessage.getText() + " | ROTANTE");
                    enableRotatingElements(foundResident);

                } else if ("WITH_PARKING".equals(foundResident.getUserType())) {
                    lblMessage.setForeground(new Color(100, 0, 0));
                    lblMessage.setText(lblMessage.getText() + " | PERMANENTE");
                    disablePaymentElements();
                }

                if (foundResident.getAssignedParkingSpace() != null) {
                    lblMessage.setText(lblMessage.getText() + " | Space: " + foundResident.getAssignedParkingSpace());
                }

            } else {
                lblMessage.setText("Resident not found: " + input);
                lblMessage.setForeground(Color.RED);

                JOptionPane.showMessageDialog(this,
                        "Resident not found: " + input,
                        "Not Found",
                        JOptionPane.WARNING_MESSAGE);

                clearFormFields();
            }

        } catch (Exception e) {
            lblMessage.setText("Search error");
            lblMessage.setForeground(Color.RED);

            JOptionPane.showMessageDialog(this,
                    "Error searching: " + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);

            clearFormFields();
        }
    }

    private void displayResidentInfo(Resident resident) {

        String displayText = resident.getName()
                + " | ID: " + resident.getResidentID()
                + " | Apt: " + resident.getApartmentNumber();

        lblMessage.setText(displayText);

        if ("ROTATING".equals(resident.getUserType())) {
            lblMessage.setForeground(new Color(0, 150, 0));
            lblMessage.setText(lblMessage.getText() + " | ROTANTE");
            enableRotatingElements(resident);

        } else if ("WITH_PARKING".equals(resident.getUserType())) {
            lblMessage.setForeground(new Color(100, 0, 0));
            lblMessage.setText(lblMessage.getText() + " | PERMANENTE");
            disablePaymentElements();

        } else {
            lblMessage.setForeground(Color.BLACK);
            lblMessage.setText(lblMessage.getText() + " | " + resident.getUserType());
            disablePaymentElements();
        }

        if (resident.getAssignedParkingSpace() != null
                && !resident.getAssignedParkingSpace().isEmpty()) {
            lblMessage.setText(lblMessage.getText() + " | Space: " + resident.getAssignedParkingSpace());
        }
    }

    private void enableRotatingElements(Resident resident) {

        lblValueToPay.setEnabled(true);
        lblMonthsOfUse.setEnabled(true);
        cmbAvailableSpaces.setEnabled(true);
        cmbMonthsSubscription.setEnabled(true);
        btnPay.setEnabled(true);
        btnPayAndRenew.setEnabled(true);

        lblValueToPay.setBackground(Color.WHITE);
        lblMonthsOfUse.setBackground(Color.WHITE);

        if (resident.getCurrentRental() != null) {
            Rental rental = resident.getCurrentRental();
            lblValueToPay.setText("$" + rental.getMonthlyPrice());

            long days = rental.getDaysRemaining();
            int months = (int) Math.ceil(days / 30.0);
            lblMonthsOfUse.setText(String.valueOf(Math.max(1, months)));

            if (cmbAvailableSpaces != null && rental.getSpaceId() != null) {
                selectSpaceInComboBox(rental.getSpaceId());
            }
        } else {
            lblValueToPay.setText("$0.00");
            lblMonthsOfUse.setText("0");
        }
    }

    private void disablePaymentElements() {
        lblValueToPay.setText("");
        lblMonthsOfUse.setText("");

        lblValueToPay.setEnabled(false);
        lblMonthsOfUse.setEnabled(false);
        cmbAvailableSpaces.setEnabled(false);
        cmbMonthsSubscription.setEnabled(false);
        btnPay.setEnabled(false);
        btnPayAndRenew.setEnabled(false);

        lblValueToPay.setBackground(Color.LIGHT_GRAY);
        lblMonthsOfUse.setBackground(Color.LIGHT_GRAY);
    }

    private void selectSpaceInComboBox(String space) {
        if (cmbAvailableSpaces != null) {
            for (int i = 0; i < cmbAvailableSpaces.getItemCount(); i++) {
                if (cmbAvailableSpaces.getItemAt(i).equals(space)) {
                    cmbAvailableSpaces.setSelectedIndex(i);
                    return;
                }
            }
        }
    }

    private void clearFormFields() {
        disablePaymentElements();
        if (cmbAvailableSpaces != null) {
            cmbAvailableSpaces.setSelectedIndex(0);
        }
        if (cmbMonthsSubscription != null) {
            cmbMonthsSubscription.setSelectedIndex(0);
        }
        String input = txtFindResident.getText().trim();

        if (input.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Ingrese el ID del residente (ej: RES-001)",
                    "Campo vacío",
                    JOptionPane.WARNING_MESSAGE);
            txtFindResident.requestFocus();
            lblMessage.setText("");
            return;
        }

        if (!input.matches("^[A-Za-z0-9-]+$")) {
            JOptionPane.showMessageDialog(this,
                    "Formato de ID inválido!\n\n"
                    + "Solo use:\n"
                    + "• Letras (A-Z, a-z)\n"
                    + "• Números (0-9)\n"
                    + "• Guiones (-)\n\n"
                    + "Ejemplo: RES-001",
                    "ID Inválido",
                    JOptionPane.ERROR_MESSAGE);

            txtFindResident.setText("");
            txtFindResident.requestFocus();
            lblMessage.setText("");
            return;
        }

        lblMessage.setText("Buscando ID: " + input + "...");
        lblMessage.setForeground(Color.BLUE);

        try {
            ResidentController controller = new ResidentController();
            Resident foundResident = controller.searchResidentById(input);

            if (foundResident != null) {

                displayResidentInfo(foundResident);
            } else {
                lblMessage.setText("No se encontró residente con ID: " + input);
                lblMessage.setForeground(Color.RED);

                JOptionPane.showMessageDialog(this,
                        "No se encontró residente con ID: " + input,
                        "No Encontrado",
                        JOptionPane.WARNING_MESSAGE);

                clearFormFields();
            }

        } catch (Exception e) {
            lblMessage.setText("Error en búsqueda");
            lblMessage.setForeground(Color.RED);

            JOptionPane.showMessageDialog(this,
                    "Error buscando por ID: " + e.getMessage(),
                    "Error de Base de Datos",
                    JOptionPane.ERROR_MESSAGE);

            clearFormFields();
        }
    }//GEN-LAST:event_btnSearchResidentActionPerformed


    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        if (lblMessage.getText().isEmpty() || !lblMessage.getText().contains("ROTANTE")) {
            JOptionPane.showMessageDialog(this,
                    "Please search for a ROTATING resident first",
                    "No Resident Selected",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String paymentValue = lblValueToPay.getText();
        String monthsUsed = lblMonthsOfUse.getText();
        String selectedSpace = (String) cmbAvailableSpaces.getSelectedItem();

        if (paymentValue.isEmpty() || paymentValue.equals("$0.00")) {
            JOptionPane.showMessageDialog(this,
                    "No payment amount calculated",
                    "Payment Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        int response = JOptionPane.showConfirmDialog(this,
                "PAYMENT CONFIRMATION\n\n"
                + "Amount to Pay: " + paymentValue + "\n"
                + "Months of Use: " + monthsUsed + "\n"
                + "Do you want to proceed with this payment?",
                "Confirm Payment",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            try {
                JOptionPane.showMessageDialog(this,
                        "PAYMENT PROCESSED SUCCESSFULLY!\n\n"
                        + "Amount: " + paymentValue + "\n"
                        + "Transaction ID: TXN-" + System.currentTimeMillis() + "\n"
                        + "Date: " + new java.util.Date(),
                        "Payment Successful",
                        JOptionPane.INFORMATION_MESSAGE);

                updateStateAfterPayment();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "PAYMENT FAILED!\n\n"
                        + "Error: " + e.getMessage(),
                        "Payment Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Payment cancelled by user",
                    "Payment Cancelled",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void updateStatusAfterPayment() {
        lblValueToPay.setText("");
        lblMonthsOfUse.setText("");

        cmbAvailableSpaces.setSelectedIndex(0);
        cmbMonthsSubscription.setSelectedIndex(0);

        lblMessage.setText("Payment completed - Resident account updated");
        lblMessage.setForeground(new Color(0, 100, 0));

        txtFindResident.setText("");
        txtFindResident.requestFocus();

        btnPay.setEnabled(false);
        btnPayAndRenew.setEnabled(false);
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnPayAndRenewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayAndRenewActionPerformed
        if (lblMessage.getText().isEmpty() || !lblMessage.getText().contains("ROTANTE")) {
            JOptionPane.showMessageDialog(this,
                    "Please search for a ROTATING resident first",
                    "No Resident Selected",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String paymentValue = lblValueToPay.getText();
        String monthsUsed = lblMonthsOfUse.getText();
        String selectedSpace = (String) cmbAvailableSpaces.getSelectedItem();
        String renewalPeriod = (String) cmbMonthsSubscription.getSelectedItem();

        if (paymentValue.isEmpty() || paymentValue.equals("$0.00")) {
            JOptionPane.showMessageDialog(this,
                    "No payment amount calculated",
                    "Payment Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        int response = JOptionPane.showConfirmDialog(this,
                "PAYMENT & RENEWAL CONFIRMATION\n\n"
                + "Payment Details:\n"
                + "• Amount to Pay: " + paymentValue + "\n"
                + "• Current Months: " + monthsUsed + "\n"
                + "Renewal Details:\n"
                + "• Renewal Period: " + renewalPeriod + "\n"
                + "• New End Date: " + calculateEndDate(renewalPeriod) + "\n\n"
                + "Do you want to proceed with PAYMENT AND RENEWAL?",
                "Confirm Payment & Renewal",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.YES_OPTION) {
            try {
                String newEndDate = calculateEndDate(renewalPeriod);

                JOptionPane.showMessageDialog(this,
                        "PAYMENT & RENEWAL PROCESSED SUCCESSFULLY!\n\n"
                        + "Payment Details:\n"
                        + "• Amount Paid: " + paymentValue + "\n"
                        + "• Transaction ID: REN-" + System.currentTimeMillis() + "\n\n"
                        + "Renewal Details:\n"
                        + "• Renewal Period: " + renewalPeriod + "\n"
                        + "• New End Date: " + newEndDate + "\n",
                        "Payment & Renewal Successful",
                        JOptionPane.INFORMATION_MESSAGE);

                updateStateAfterRenewal(newEndDate);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "PAYMENT & RENEWAL FAILED!\n\n"
                        + "Error: " + e.getMessage(),
                        "Processing Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this,
                    "Payment & renewal cancelled by user",
                    "Cancelled",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void updateStateAfterPayment() {
        lblValueToPay.setText("");
        lblMonthsOfUse.setText("");

        cmbAvailableSpaces.setSelectedIndex(0);
        cmbMonthsSubscription.setSelectedIndex(0);

        lblMessage.setText("Payment completed - Resident account updated");
        lblMessage.setForeground(new Color(0, 100, 0));

        txtFindResident.setText("");
        txtFindResident.requestFocus();

        btnPay.setEnabled(false);
        btnPayAndRenew.setEnabled(false);
    }

    private void updateStateAfterRenewal(String newEndDate) {
        lblValueToPay.setText("");
        lblMonthsOfUse.setText("");

        lblMessage.setText("Payment & renewal completed - Valid until: " + newEndDate);
        lblMessage.setForeground(new Color(0, 100, 0));

        txtFindResident.setText("");
        txtFindResident.requestFocus();

        btnPay.setEnabled(false);
        btnPayAndRenew.setEnabled(false);
    }

    private String calculateEndDate(String renewalPeriod) {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy");
        java.util.Calendar cal = java.util.Calendar.getInstance();

        int months = 1;
        if (renewalPeriod.contains("2")) {
            months = 2;
        } else if (renewalPeriod.contains("3")) {
            months = 3;
        } else if (renewalPeriod.contains("6")) {
            months = 6;
        } else if (renewalPeriod.contains("12")) {
            months = 12;
        }

        cal.add(java.util.Calendar.MONTH, months);
        return sdf.format(cal.getTime());
    }//GEN-LAST:event_btnPayAndRenewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmResidentRental().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPayAndRenew;
    private javax.swing.JButton btnSearchResident;
    private javax.swing.JComboBox<String> cmbAvailableSpaces;
    private javax.swing.JComboBox<String> cmbMonthsSubscription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblMonthsOfUse;
    private javax.swing.JLabel lblSelectedSpace;
    private javax.swing.JLabel lblValueToPay;
    private javax.swing.JTextField txtFindResident;
    // End of variables declaration//GEN-END:variables
}
