# ==========================
# Constantes de la simulación
# ==========================
MAX_ANT_WEIGHT = 5.0
MIN_WEIGHT_TO_LEAVE_NEST = 3.0
FOOD_CARRY_CAPACITY = 5
PHEROMONE_MAX_STRENGTH = 100
WEIGHT_DECREASE_TICKS = 50 
WEIGHT_DECREASE_AMOUNT = 1.0 
ANT_EATER_DIGEST_TICKS = 10
PHEROMONE_DECAY_RATE = 1