package ec.edu.espe.crudstrategy.view;

/**
 *
 * @author Adrian Toapanta 
 */
import ec.edu.espe.crudstrategy.controller.CustomerController;
import ec.edu.espe.crudstrategy.model.Customer;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmRead extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRead.class.getName());

    private CustomerController controller;
    private DefaultTableModel tableModel;

    /**
     * Creates new form FrmRead
     */
    public FrmRead() {
        initComponents();
        controller = new CustomerController();
        initializeTable();
        setLocationRelativeTo(null);
        loadAllFilesOption();
    }

    private void initializeTable() {
        tableModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        String[] columns = {"ID", "Name", "Email", "Phone"};
        for (String column : columns) {
            tableModel.addColumn(column);
        }
        
        tableInfo.setModel(tableModel);
        tableInfo.getTableHeader().setReorderingAllowed(false);
    }
    
    private void loadAllFilesOption() {
        cbxFile.removeAllItems();
        cbxFile.addItem("Select a format...");
        cbxFile.addItem("JSON");
        cbxFile.addItem("CSV");
        cbxFile.addItem("MongoDB");
        cbxFile.addItem("ALL (All formats)");
        cbxFile.setSelectedIndex(0);
    }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxFile = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableInfo = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Read");

        jLabel2.setText("Select an option");

        cbxFile.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Json", "Csv", "MongoDB", "All" }));

        btnSearch.setText("Search");
        btnSearch.addActionListener(this::btnSearchActionPerformed);

        tableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Phone"
            }
        ));
        jScrollPane1.setViewportView(tableInfo);

        jMenu1.setText("System");

        jMenuItem1.setText("Return to Menu");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(211, 211, 211))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbxFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSearch)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String selectedOption = (String) cbxFile.getSelectedItem();
        
        if (selectedOption == null || selectedOption.equals("Select a format...")) {
            JOptionPane.showMessageDialog(this,
                "Please select a format",
                "Required selection", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            if (selectedOption.equals("ALL (All formats)")) {
                loadAllFormats();
            } else {
                loadSingleFormat(selectedOption);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error loading data: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmMenu frmMenu = new FrmMenu();
        frmMenu. setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    private void loadSingleFormat(String format) {
        tableModel.setRowCount(0);
        
        controller.setStorageType(format);
        
        List<Customer> customers = controller.getAllCustomers();
        
        if (customers.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "No clients were found in the format " + format,
                "Sin datos", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        for (Customer customer : customers) {
            Object[] row = {
                customer.getId(),
                customer.getName(),
                customer.getEmail(),
                customer.getPhone()
            };
            tableModel.addRow(row);
        }
        
    }
    
    private void loadAllFormats() {
        tableModel.setRowCount(0);
        
        int totalCustomers = 0;
        
        controller.setStorageType("JSON");
        List<Customer> jsonCustomers = controller.getAllCustomers();
        addCustomersToTable(jsonCustomers, "JSON");
        totalCustomers += jsonCustomers.size();
        
        controller.setStorageType("CSV");
        List<Customer> csvCustomers = controller.getAllCustomers();
        addCustomersToTable(csvCustomers, "CSV");
        totalCustomers += csvCustomers.size();
        
        controller.setStorageType("MongoDB");
        List<Customer> mongoCustomers = controller.getAllCustomers();
        addCustomersToTable(mongoCustomers, "MongoDB");
        totalCustomers += mongoCustomers.size();
        
        if (totalCustomers == 0) {
            JOptionPane.showMessageDialog(this,
                "No customers were found in any format.",
                "Sin datos", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }
    
    private void addCustomersToTable(List<Customer> customers, String source) {
        for (Customer customer : customers) {
            Object[] row = {
                customer.getId(),
                customer.getName(),
                customer.getEmail(),
                customer.getPhone(),
                source  
            };
            tableModel.addRow(row);
        }
    }
    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmRead().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbxFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableInfo;
    // End of variables declaration//GEN-END:variables

}
