const crypto = require('crypto');
const { 
    QMainWindow, QWidget, QLabel, QLineEdit, QGridLayout, 
    QPushButton, QComboBox, QRadioButton, QPlainTextEdit, 
    QListWidget, QListWidgetItem, QMessageBox, SelectionMode,
    QDateEdit, 
    QDate
} = require("@nodegui/nodegui");

const Contact = require('../contactsBookModel/Contact.js');
const ContactManager = require('../contactsBookController/ContactManager.js');
<<<<<<< HEAD
const JavaScriptValidator = require('../contactsBookUtils/GUIValidation.js'); 
=======
<<<<<<< HEAD

=======
const JavaScriptValidator = require('../contactsBookUtils/GUIValidation.js'); 
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
>>>>>>> 58e5d161bc1779e9dbf6e4ea38d18547b28d0a4e
const win = new QMainWindow();
win.setWindowTitle("Contacts Book");
win.resize(800, 600);

const centralWidget = new QWidget();
win.setCentralWidget(centralWidget);

const rootLayout = new QGridLayout();
centralWidget.setLayout(rootLayout);

<<<<<<< HEAD
const STYLE_ERROR = "border: 2px solid red;";
const STYLE_NORMAL = "border: 1px solid gray;"; 

=======
<<<<<<< HEAD
=======
const STYLE_ERROR = "border: 2px solid red;";
const STYLE_NORMAL = "border: 1px solid gray;"; 

>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
>>>>>>> 58e5d161bc1779e9dbf6e4ea38d18547b28d0a4e
const lblTitle = new QLabel();
lblTitle.setText("CONTACTS");
lblTitle.setInlineStyle("font-size: 24px; font-weight: bold; margin-bottom: 20px;");
rootLayout.addWidget(lblTitle, 0, 0, 1, 4); 

const lblId = new QLabel(); lblId.setText("id:");
const lblIdVal = new QLabel(); lblIdVal.setText("(autogenerated)"); 
rootLayout.addWidget(lblId, 1, 0);
rootLayout.addWidget(lblIdVal, 1, 1);

const lblFirst = new QLabel(); lblFirst.setText("First Name:");
const txtFirst = new QLineEdit();
rootLayout.addWidget(lblFirst, 2, 0);
rootLayout.addWidget(txtFirst, 2, 1);

const lblLast = new QLabel(); lblLast.setText("Last Name:");
const txtLast = new QLineEdit();
rootLayout.addWidget(lblLast, 3, 0);
rootLayout.addWidget(txtLast, 3, 1);

const lblAge = new QLabel(); lblAge.setText("Age:");
rootLayout.addWidget(lblAge, 4, 0);

const lblType = new QLabel(); lblType.setText("Type:");
const cmbType = new QComboBox();
cmbType.addItems(["Family", "Friend", "Job", "Unknown"]);
rootLayout.addWidget(lblType, 5, 0);
rootLayout.addWidget(cmbType, 5, 1);

const lblSex = new QLabel(); lblSex.setText("Sex:");
const radMale = new QRadioButton(); radMale.setText("Male");
const radFemale = new QRadioButton(); radFemale.setText("Female");
radMale.setChecked(true);

const sexWidget = new QWidget();
const sexLayout = new QGridLayout();
sexWidget.setLayout(sexLayout);
sexLayout.addWidget(radMale, 0, 0);
sexLayout.addWidget(radFemale, 1, 0);

rootLayout.addWidget(lblSex, 6, 0);
rootLayout.addWidget(sexWidget, 6, 1);

const lblHobbies = new QLabel(); lblHobbies.setText("Hobbies:");
const lstHobbies = new QListWidget();
const hobbiesData = ["Play Soccer", "Djing", "Read", "Cook", "Swim", "Sing", "Instrument"];
hobbiesData.forEach(h => {
    const item = new QListWidgetItem();
    item.setText(h);
    lstHobbies.addItem(item);
});
lstHobbies.setSelectionMode(SelectionMode.MultiSelection);
rootLayout.addWidget(lblHobbies, 7, 0);
rootLayout.addWidget(lstHobbies, 7, 1);

const lblDate = new QLabel(); 
lblDate.setText("Birthday:");
const txtDate = new QDateEdit();

txtDate.setCalendarPopup(true); 

const now = new Date();
const qNow = new QDate();
qNow.setDate(now.getFullYear(), now.getMonth() + 1, now.getDate());
txtDate.setDate(qNow);

rootLayout.addWidget(lblDate, 8, 0);
rootLayout.addWidget(txtDate, 8, 1);


const lblComments = new QLabel(); 
lblComments.setText("Comments:");
const txtComments = new QPlainTextEdit();
rootLayout.addWidget(lblComments, 1, 2);
rootLayout.addWidget(txtComments, 1, 3, 7, 1);

const btnSave = new QPushButton();
btnSave.setText("Save");
rootLayout.addWidget(btnSave, 9, 0, 1, 4);

<<<<<<< HEAD
function showError(message, field) {
    const errBox = new QMessageBox();
    errBox.setWindowTitle("Validation Error");
    errBox.setText(message);
    errBox.exec();

    if (field) {
        field.setInlineStyle(STYLE_ERROR);
        field.setFocus(true);
    }
}

=======
<<<<<<< HEAD
>>>>>>> 58e5d161bc1779e9dbf6e4ea38d18547b28d0a4e
btnSave.addEventListener("clicked", async () => {

    const firstName = txtFirst.text();
    const lastName = txtLast.text();
    
    const birthdayQDate = txtDate.date();
    const birthdayString = `${birthdayQDate.year()}-${birthdayQDate.month()}-${birthdayQDate.day()}`;

    txtFirst.setInlineStyle(STYLE_NORMAL);
    txtLast.setInlineStyle(STYLE_NORMAL);
    txtDate.setInlineStyle(STYLE_NORMAL);
    
    if (!JavaScriptValidator.isNotEmpty(firstName)) {
        showError("First Name cannot be empty.", txtFirst);
        return;
    }
    if (!JavaScriptValidator.isValidName(firstName)) {
        showError("First Name contains invalid characters (only letters, spaces, dots, and hyphens).", txtFirst);
        return;
    }

    if (!JavaScriptValidator.isNotEmpty(lastName)) {
        showError("Last Name cannot be empty.", txtLast);
        return;
    }
    if (!JavaScriptValidator.isValidName(lastName)) {
        showError("Last Name contains invalid characters (only letters, spaces, dots, and hyphens).", txtLast);
        return;
    }

    if (!JavaScriptValidator.isDateNotFuture(birthdayString)) {
        showError("Birthday cannot be a future date.", txtDate);
        return;
    }
    
    const id = crypto.randomUUID();
    const age = 19; 
    const typeOfContact = cmbType.currentText();
    let sex = radFemale.isChecked() ? "Female" : "Male";
    const selectedItems = lstHobbies.selectedItems();
    const hobbies = selectedItems.map(item => item.text());
    const comments = txtComments.toPlainText();
<<<<<<< HEAD
    const birthday = txtDate.text(); 
=======
=======
function showError(message, field) {
    const errBox = new QMessageBox();
    errBox.setWindowTitle("Validation Error");
    errBox.setText(message);
    errBox.exec();

    if (field) {
        field.setInlineStyle(STYLE_ERROR);
        field.setFocus(true);
    }
}

btnSave.addEventListener("clicked", async () => {

    const firstName = txtFirst.text();
    const lastName = txtLast.text();
    
    const birthdayQDate = txtDate.date();
    const birthdayString = `${birthdayQDate.year()}-${birthdayQDate.month()}-${birthdayQDate.day()}`;

    txtFirst.setInlineStyle(STYLE_NORMAL);
    txtLast.setInlineStyle(STYLE_NORMAL);
    txtDate.setInlineStyle(STYLE_NORMAL);
    
    if (!JavaScriptValidator.isNotEmpty(firstName)) {
        showError("First Name cannot be empty.", txtFirst);
        return;
    }
    if (!JavaScriptValidator.isValidName(firstName)) {
        showError("First Name contains invalid characters (only letters, spaces, dots, and hyphens).", txtFirst);
        return;
    }

    if (!JavaScriptValidator.isNotEmpty(lastName)) {
        showError("Last Name cannot be empty.", txtLast);
        return;
    }
    if (!JavaScriptValidator.isValidName(lastName)) {
        showError("Last Name contains invalid characters (only letters, spaces, dots, and hyphens).", txtLast);
        return;
    }

    if (!JavaScriptValidator.isDateNotFuture(birthdayString)) {
        showError("Birthday cannot be a future date.", txtDate);
        return;
    }
    
    const id = crypto.randomUUID();
    const age = 19; 
    const typeOfContact = cmbType.currentText();
    let sex = radFemale.isChecked() ? "Female" : "Male";
    const selectedItems = lstHobbies.selectedItems();
    const hobbies = selectedItems.map(item => item.text());
    const comments = txtComments.toPlainText();
    const birthday = txtDate.text(); 
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
>>>>>>> 58e5d161bc1779e9dbf6e4ea38d18547b28d0a4e
    
    const newContact = new Contact(id, firstName, lastName, age, typeOfContact, sex, hobbies, comments);
    
    const confirmationBox = new QMessageBox();
    confirmationBox.setWindowTitle("SAVE CONTACTS?");
    confirmationBox.setText(`Do you want to save the contact ${firstName} ${lastName}? \nBirthday: ${birthday} \n\n${newContact.toString()}`);
    
    const btnYes = new QPushButton();
    btnYes.setText("Yes, Save");
    
    const btnNo = new QPushButton();
    btnNo.setText("No, Cancel");
    confirmationBox.addButton(btnYes, 0); 
    confirmationBox.addButton(btnNo, 1);

    btnYes.addEventListener('clicked', async () => {
        confirmationBox.close();
        
        try {
            const saved = await ContactManager.save(newContact);
            
            if (saved) {
                const infoBox = new QMessageBox();
                infoBox.setWindowTitle("SUCCESS");
                infoBox.setText("Successfully saved.");
                const btnOk = new QPushButton();
                btnOk.setText("OK");
                infoBox.addButton(btnOk, 0);
                infoBox.exec();
<<<<<<< HEAD
                
=======
<<<<<<< HEAD

=======
                
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
>>>>>>> 58e5d161bc1779e9dbf6e4ea38d18547b28d0a4e
                txtFirst.setText("");
                txtLast.setText("");
                txtComments.setPlainText("");
                cmbType.setCurrentIndex(0); 
                radMale.setChecked(true); 
                lstHobbies.clearSelection(); 
                txtDate.setDate(qNow);
<<<<<<< HEAD
=======
<<<<<<< HEAD

=======
>>>>>>> 95b5ff6cf684ae826e202c2e63b274c2ad0a5ba8
>>>>>>> 58e5d161bc1779e9dbf6e4ea38d18547b28d0a4e
            } else {
                const errBox = new QMessageBox();
                errBox.setWindowTitle("ERROR");
                errBox.setText("Could not save.");
                errBox.exec();
            }
        } catch (error) {
            console.log(error);
        }
    });

    btnNo.addEventListener('clicked', () => {
        confirmationBox.close(); 
        
        const warnBox = new QMessageBox();
        warnBox.setWindowTitle("CANCELLED");
        warnBox.setText("Operation cancelled. Data not saved.");
        warnBox.exec();
    });

    confirmationBox.exec(); 
});

win.show();
global.win = win;